server:
  port: 9001

spring:
  application:
    name: user-service
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
# h2 test DB를 사용중이기 때문에 datasource 아래엔 생략 가능.

greeting:
  name: Welcome User Service Platform

# Swagger UI 설정
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
