server:
  port: 9001

spring:
  application:
    name: user-service
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

greeting:
  name: Welcome User Service Platform
